### ISSUE TITLE
PostgreSQL 9.6 -- IsForeignScanParallelSafe

### ISSUE THREAD

**Issue by rotten** [komamitsu/td-fdw#4]
One of the most important new features in PostgreSQL 9.6 are parallel query capabilities.

In the documentation on the subject:
https://www.postgresql.org/docs/9.6/static/parallel-safety.html

They mention this bullet item with little else to illuminate the topic:

> The following operations are always parallel restricted.
> - Scans of foreign tables, unless the foreign data wrapper has an IsForeignScanParallelSafe API which indicates otherwise.

It isn't clear yet to me if FDW developers have to implement something special to support this option, or if you just tell PostgreSQL it is a safe API and use it.  It also isn't clear if td-fdw would be parallel scan safe or not...

Thoughts?

**Comment by rotten** [comment]
ps:  I'll ask the same question on the Multicorn issue page because I don't see any mention of this new feature either.

**Comment by komamitsu** [comment]
I guess Multicorn won't call IsForeignScanParallelSafe API and provide a way to change parallel safety type. So td-fdw will run with parallel restricted type in PostgreSQL 9.6 or later and it sounds safe.

As for a benefit of parallel query with td-fdw, I don't think it improves the performance of query processing well since queries issued to Treasure Data via td-fdw take time mainly for computation in Treasure Data using Hive or Presto. But if you download a huge result data from Treasure Data using td-fdw, parallel scan might improve the performance.

**Comment by rotten** [comment]
We usually put materialized views in front of our foreign tables, and then refresh them.  I don't think PostgreSQL 9.6 will update a materialized view in parallel yet, so it probably won't make any difference in the refresh time.   I'll still try it though. I'll do some testing once I get our new PG 9.6 server online within the next couple of weeks.

**Comment by rotten** [comment]
Just to follow up on this.   Refreshing a materialized view does not use the new parallelization feature, data changing queries are necessarily single threaded at this time.  The query planning for foreign tables appears to be left to the foreign database, so that feature has no direct effect in 9.6.
